apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-microservices
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/meirelless/meu-lab-cluster'
    targetRevision: HEAD
    path: k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
