apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-mysql
  template:
    metadata:
      labels:
        app: crud-mysql
    spec:
      containers:
      - name: crud-mysql
        image: franciscomeirelles/crud-mysql:latest   # <--- mudou aqui
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: crud-mysql
spec:
  type: ClusterIP
  ports:
  - port: 8000
  selector:
    app: crud-mysql
