apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-postgres
  template:
    metadata:
      labels:
        app: crud-postgres
    spec:
      containers:
      - name: crud-postgres
        image: franciscomeirelles/crud-postgres:latest   # <--- Docker Hub
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: crud-postgres
spec:
  type: ClusterIP
  ports:
  - port: 8000
  selector:
    app: crud-postgres
