apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-php
  template:
    metadata:
      labels:
        app: frontend-php
    spec:
      containers:
      - name: frontend-php
        image: franciscomeirelles/frontend-php:latest   # <--- Docker Hub
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-php
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080    # porta exposta pelo Minikube
  selector:
    app: frontend-php
